version: "3.8"

services:
  api:
    build: ./api
    container_name: api_nube
    volumes:
      - ${PWD}/var/videos/outs:/var/videos/outs
      - ${PWD}/var/videos/ins:/var/videos/ins
    working_dir: /backend/
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=6000
      - URL_HOST_BASE=${URL_HOST_BASE}
      - HOST_QUEUE=${HOST_QUEUE}
      - PORT_QUEUE=61613
      - NAME_QUEUE='videos'
      - USER_QUEUE=${USER_QUEUE}
      - PWD_QUEUE=${PWD_QUEUE}
      - IN_EXT_VIDEOS=mp4
      - IN_FILE_VIDEOS=/var/videos/ins
      - HOST_PG=${HOST_PG}
      - PORT_PG=5432
      - USER_PG=${USER_PG}
      - PWD_PG=${PWD_PG}
      - DB_NAME_PG=videos
    ports:
      - "6000:6000"
    command: bash -c "echo 'Starting Api' && python api.py"