version: "3.3"

services:
  api:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2000m'
        reservations:
          memory: '256m'
    build: ./api
    container_name: api_nube
    working_dir: /backend/
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=6000
      - URL_HOST_BASE=${URL_HOST_BASE}
      - HOST_QUEUE=${HOST_QUEUE}
      - PORT_QUEUE=61613
      - NAME_QUEUE=videos
      - USER_QUEUE=${USER_QUEUE}
      - PWD_QUEUE=${PWD_QUEUE}
      - IN_EXT_VIDEOS=mp4
      - IN_FILE_VIDEOS=/videos/ins
      - HOST_PG=${HOST_PG}
      - PORT_PG=5432
      - USER_PG=${USER_PG}
      - PWD_PG=${PWD_PG}
      - DB_NAME_PG=videos
      - IN_GS_FILE_VIDEOS=ins
      - GCLOUD_PROJECT=soluciones-cloud-202402
      - GCLOUD_BUCKET=soluciones-cloud-202402-videos2
      - QUEUE_CLOUD_PROVIDER=true
      - NAME_SUB=videos-sub
    ports:
      - "6000:6000"
      - "80:6000"
    command: bash -c "echo 'Starting Api' && python api.py"