version: "3.3"

services:
  worker:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2000m'
        reservations:
          memory: '256m'
    build: ./worker
    container_name: worker_nube
    working_dir: /backend/
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_QUEUE=${HOST_QUEUE}
      - PORT_QUEUE=61613
      - NAME_QUEUE=videos
      - USER_QUEUE=${USER_QUEUE}
      - PWD_QUEUE=${PWD_QUEUE}
      - OUT_EXT_VIDEOS=mp4
      - MAX_DIRECTION_VIDEOS=20
      - OUT_FILE_VIDEOS=/videos/outs
      - HOST_PG=${HOST_PG}
      - PORT_PG=5432
      - USER_PG=${USER_PG}
      - PWD_PG=${PWD_PG}
      - DB_NAME_PG=videos
      - OUT_GS_FILE_VIDEOS=outs
      - GCLOUD_PROJECT=soluciones-cloud-202402
      - GCLOUD_BUCKET=soluciones-cloud-202402-videos2
    command: bash -c "echo Starting worker videos && python init_bd.py && python process.py"