version: "3.3"

services:
  queue:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          memory: '256m'
    image: apache/activemq-classic
    container_name: queue_nube
    environment:
      ACTIVEMQ_OPTS: "-Djetty.host=0.0.0.0 -Djava.util.logging.config.file=logging.properties -Djava.security.auth.login.config=/opt/apache-activemq/conf/login.config"
    ports:
      - "61616:61616"
      - "61613:61613"
      - "61614:61614"
      - "8161:8161"
    healthcheck:
      test: /opt/apache-activemq/bin/activemq query --objname type=Broker,brokerName=*,service=Health | grep Good
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          memory: '256m'
    image: postgres:14-alpine
    container_name: postgres_nube
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
      - ${PWD}/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=videos
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1000m'
        reservations:
          memory: '256m'
    build: ./worker
    container_name: worker_nube
    working_dir: /backend/
    volumes:
      - ./wait:/wait
      - shared-volume:/backend/videos/ins
      - shared-volume:/backend/videos/outs
    depends_on:
      - queue
      - postgres
    environment:
      WAIT_HOSTS: queue:61613,postgres:5432
      WAIT_TIMEOUT: 200
      PYTHONUNBUFFERED: 1
      HOST_QUEUE: 'queue'
      PORT_QUEUE: 61613
      NAME_QUEUE: 'videos'
      USER_QUEUE: 'admin'
      PWD_QUEUE: 'admin'
      OUT_EXT_VIDEOS: 'mp4'
      MAX_DIRECTION_VIDEOS: 20
      OUT_FILE_VIDEOS: /backend/videos/outs
      HOST_PG: 'postgres'
      PORT_PG: 5432
      USER_PG: 'postgres'
      PWD_PG: 'postgres'
      DB_NAME_PG: 'videos'
    command: bash -c "chmod +x /wait && /wait && echo 'Starting worker videos' && python init_bd.py && python process.py"

  api:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          memory: '256m'
    build: ./api
    container_name: api_nube
    working_dir: /backend/
    volumes:
      - ./wait:/wait
      - shared-volume:/backend/videos/ins
      - shared-volume:/backend/videos/outs
    depends_on:
      - queue
      - postgres
    environment:
      WAIT_HOSTS: queue:61613,postgres:5432
      WAIT_TIMEOUT: 200
      PYTHONUNBUFFERED: 1
      PORT: 6000
      URL_HOST_BASE: 'http://127.0.0.1:6000'
      HOST_QUEUE: 'queue'
      PORT_QUEUE: 61613
      NAME_QUEUE: 'videos'
      USER_QUEUE: 'admin'
      PWD_QUEUE: 'admin'
      IN_EXT_VIDEOS: 'mp4'
      IN_FILE_VIDEOS: /backend/videos/ins
      HOST_PG: 'postgres'
      PORT_PG: 5432
      USER_PG: 'postgres'
      PWD_PG: 'postgres'
      DB_NAME_PG: 'videos'
      API_KEY: 'ApiKeyTestLoadGp10'
    ports:
      - "6000:6000"
    command: bash -c "chmod +x /wait && /wait && echo 'Starting Api' && python api.py"

volumes:
  shared-volume: