version: "3.3"

services:
  postgres:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512m'
        reservations:
          memory: '256m'
    image: postgres:14-alpine
    container_name: postgres_nube
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
      - ${PWD}/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=videos
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1000m'
        reservations:
          memory: '256m'
    build: ./worker
    container_name: worker_nube
    working_dir: /backend/
    volumes:
      - ./wait:/wait
      - shared-volume:/backend/videos/ins
      - shared-volume:/backend/videos/outs
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 200
      PYTHONUNBUFFERED: 1
      HOST_QUEUE: 'queue'
      PORT_QUEUE: 61613
      NAME_QUEUE: 'videos'
      USER_QUEUE: 'admin'
      PWD_QUEUE: 'admin'
      OUT_EXT_VIDEOS: 'mp4'
      MAX_DIRECTION_VIDEOS: 20
      OUT_FILE_VIDEOS: /backend/videos/outs
      OUT_GS_FILE_VIDEOS: outs
      HOST_PG: 'postgres'
      PORT_PG: 5432
      USER_PG: 'postgres'
      PWD_PG: 'postgres'
      DB_NAME_PG: 'videos'
      GCLOUD_PROJECT: 'soluciones-cloud-202402'
      GCLOUD_BUCKET: 'soluciones-cloud-202402-videos2'
      GOOGLE_APPLICATION_CREDENTIALS: './soluciones-cloud-202402-77732d25e1e5.json'
      QUEUE_CLOUD_PROVIDER: 'true'
      NAME_SUB: 'videos-sub'
    command: bash -c "chmod +x /wait && /wait && echo 'Starting worker videos' && python init_bd.py && python main.py"
    ports:
      - "6001:6001"
volumes:
  shared-volume: